### ISSUE TITLE
Alien::Build

### ISSUE THREAD

**Issue by mohawk2** [majensen/neoclient#3]
Have you looked at using `Alien::Build` (or at least `ExtUtils::Depend`) to make this module smaller and/or simpler? Also, your `META_MERGE` doesn't work because you need a `meta-spec`.

**Comment by majensen** [comment]
Thanks @mohawk2 - sorry I missed this. I'm sure you are right - I will look into Alien::Build.

**Comment by majensen** [comment]
Wow - yeah - I should use it.

**Comment by mohawk2** [comment]
I'd really like to see this module be much easier to maintain for you, and more installable by users, leveraging the mighty @plicease's work!

**Comment by majensen** [comment]
If it is as cool as it looks, maybe I can dispense with this kludge altogether and wrap it into Neo4j::Bolt directly.

**Comment by mohawk2** [comment]
https://metacpan.org/pod/Alien::Build indicates that 1435 modules directly or indirectly depend on it. Hopefully that counts as cool enough? :-)

**Comment by majensen** [comment]
Ok @mohawk2 - if you have time, can you check this out:
https://github.com/majensen/neoclient/tree/feat(alien)

**Comment by mohawk2** [comment]
@majensen I've had a look, seems great! Does it work? And I'd suggest *not* incorporating this into Neo4j::Bolt, because separating the parts is good practice, and in fact the whole motivating idea behind the "Alien" concept in the first place :-)

**Comment by majensen** [comment]
Thanks @mohawk2 ! I agree, I will leave it separate. Does it work.....wellll, it's at the "works for me" stage, but still futzing.

**Comment by mohawk2** [comment]
Maybe a dev-release would help? In any case, thank you for your efforts, and feel free to close this issue if/when you feel it's done :-)

**Comment by majensen** [comment]
I think we're there - we'll see what CPANTesters has to say...

**Comment by mohawk2** [comment]
Huzzah!
